var dataMat = [
    [
     [{
       name:'谭延闿',
       type:'骑兵',
       maxMorale:3,
       morale:3,
       maxStrength:100,
       strength:67,
       I:4,
       W:4,
       B:3,
       exp:40,
       lv:0,
       buff:-0.17
      },
      {
       name:'朱培德',
       type:'新军步兵',
       maxMorale:3,
       morale:3,
       maxStrength:140,
       strength:109,
       I:4,
       W:3,
       B:3,
       exp:10,
       lv:2,
       buff:-0.06
      }
     ],
     [
      {
       name:'张辉瓒',
       type:'民兵',
       maxMorale:2,
       morale:2,
       maxStrength:100,
       strength:109,
       I:4,
       W:3,
       B:2,
       exp:0,
       lv:1,
       buff:-0.12
      },
      {
       name:'蒋中正',
       type:'黄埔步兵',
       maxMorale:5,
       morale:3,
       maxStrength:160,
       strength:110,
       I:4,
       W:4,
       B:4,
       exp:10,
       lv:3,
       buff:-0.16
      }
     ],
     [
      {
       name:'王柏龄',
       type:'炮兵',
       maxMorale:2,
       morale:2,
       maxStrength:110,
       strength:16,
       I:2,
       W:2,
       B:3,
       exp:31,
       lv:0,
       buff:-0.32
      },
      {
       name:'张治中',
       type:'民兵',
       maxMorale:2,
       morale:2,
       maxStrength:130,
       strength:130,
       I:3,
       W:3,
       B:2,
       exp:7,
       lv:1,
       buff:-0.12
      }
     ]
    ],
    [
     [
      {
       name:'刘文辉',
       type:'炮兵',
       maxMorale:2,
       morale:2,
       maxStrength:80,
       strength:80,
       I:2,
       W:2,
       B:3,
       exp:0,
       lv:1,
       buff:0.1
      },
      {
       name:'杨森',
       type:'民兵',
       maxMorale:3,
       morale:2,
       maxStrength:130,
       strength:112,
       I:3,
       W:3,
       B:2,
       exp:0,
       lv:1,
       buff:0.15
      }
     ],
     [
      {
       name:'何光烈',
       type:'民兵',
       maxMorale:3,
       morale:2,
       maxStrength:100,
       strength:100,
       I:3,
       W:3,
       B:2,
       exp:0,
       lv:0,
       buff:0.15
      },
      {
       name:'孙云',
       type:'骑兵',
       maxMorale:4,
       morale:1,
       maxStrength:110,
       strength:80,
       I:4,
       W:4,
       B:2,
       exp:59,
       lv:1,
       buff:0.15
      }
     ],
     [
      {
       name:'范绍增',
       type:'民兵',
       maxMorale:2,
       morale:1,
       maxStrength:100,
       strength:20,
       I:3,
       W:3,
       B:2,
       exp:0,
       lv:0,
       buff:0.1
      },
      {
       name:'吴传心',
       type:'民兵',
       maxMorale:2,
       morale:1,
       maxStrength:100,
       strength:100,
       I:3,
       W:3,
       B:2,
       exp:0,
       lv:0,
       buff:0.15
      }
     ]
    ]
]