var dataMat = [
    [
     [undefined,undefined
     ],
     [
      {
       name:'张辉瓒',
       type:'民兵',
       maxMorale:2,
       morale:2,
       maxStrength:100,
       strength:109,
       I:4,
       W:3,
       B:2,
       exp:0,
       lv:1,
       buff:-0.12
      },
      {
       name:'蒋中正',
       type:'黄埔步兵',
       maxMorale:5,
       morale:3,
       maxStrength:160,
       strength:110,
       I:4,
       W:4,
       B:4,
       exp:10,
       lv:3,
       buff:-0.16
      }
     ],
     [
      undefined,
      undefined
     ]
    ],
    [
     [
      undefined,
      {
       name:'杨森',
       type:'民兵',
       maxMorale:3,
       morale:2,
       maxStrength:130,
       strength:112,
       I:3,
       W:3,
       B:2,
       exp:0,
       lv:1,
       buff:0.15
      }
     ],
     [
      {
       name:'何光烈',
       type:'民兵',
       maxMorale:3,
       morale:2,
       maxStrength:100,
       strength:100,
       I:3,
       W:3,
       B:2,
       exp:0,
       lv:0,
       buff:0.15
      },
      {
       name:'孙云',
       type:'骑兵',
       maxMorale:4,
       morale:1,
       maxStrength:110,
       strength:80,
       I:4,
       W:4,
       B:2,
       exp:59,
       lv:1,
       buff:0.15
      }
     ],
     [
      {
       name:'范绍增',
       type:'民兵',
       maxMorale:2,
       morale:1,
       maxStrength:100,
       strength:20,
       I:3,
       W:3,
       B:2,
       exp:0,
       lv:0,
       buff:0.1
      },
      {
       name:'吴传心',
       type:'民兵',
       maxMorale:2,
       morale:1,
       maxStrength:100,
       strength:100,
       I:3,
       W:3,
       B:2,
       exp:0,
       lv:0,
       buff:0.15
      }
     ]
    ]
]